### ISSUE TITLE
Setup towncrier for release notes

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/eth-typing#16]
## What was wrong?

Release Notes are handled manually which is labor intensive and error prone

## How can it be fixed?

Migrate to towncrier like we did [here](https://github.com/ethereum/lahja/commit/1423150d1b286d1c77edda5069ea8b4a91474b73)

**Comment by Patil2099** [comment]
@cburgdorf  Can I work on this issue?

**Comment by cburgdorf** [comment]
@Patil2099 Go for it!
