### ISSUE TITLE
`__init__.py` is missing

### ISSUE THREAD

**Issue by pcppcp** [ethereum/eth-typing#6]
There's no `__init__.py` in `eth-typing==1.1.0` PyPi package. Therefore, all imports of this package from other libraries will fail.

**Comment by pipermerriam** [comment]
I just checked the `tar.gz` from pypi and it does contain an `__init__.py`.

**Comment by carver** [comment]
That's an odd coincidence: I had this bug yesterday, myself. I confirmed that the init file was missing in my venv site package. `pip freeze` said that `eth-typing` was at v1.1.0. But after an uninstall and install (via `pip`), everything was fine again. Still at v1.1.0, but the init file was present.

I wonder what's causing the file to disappear...

**Comment by pcppcp** [comment]
after reinstalling it with `pip install --force eth-typing` the file is where it should be. I can confirm it is also present in the tar package, and in sources.txt as well. Strange.
