### ISSUE TITLE
Add tests to release tarball (in PyPI)

### ISSUE THREAD

**Issue by jluttine** [ethereum/eth-typing#8]
Could you include tests in the source tarball in PyPI? I think it's good practice:

- https://docs.python.org/2/distutils/sourcedist.html#specifying-the-files-to-distribute
- https://stackoverflow.com/a/20180000

This way one can run the tests after installing the package. Also, I'm currently packaging this for a Linux distro, and it would be really helpful to be able to run the tests as a part of the automatic package building process while using PyPI for the release tarballs.

(See also https://github.com/ethereum/eth-utils/issues/130)

**Comment by lemenkov** [comment]
Hello!
Is there any progress here? It would be really good if you add tests to PyPi tarball as well.

**Comment by kclowes** [comment]
This issue was lost to the sands of time, and I just saw it again going through old issues. I don't see a problem including tests. Added PR #46.
